.PHONY:
run:
	node lib/main.js

.PHONY:
debug:
	#./node_modules/.bin/node-inspector --debug lib/tests/test_ptcounter.js
	#./node_modules/.bin/node-debug lib/tests/test_ptcounter.js
	./node_modules/.bin/node-debug lib/main.js

.PHONY:
test:
	node lib/tests/test_ptcounter.js
